name: Deploy

on:
  workflow_dispatch:
    inputs:
      artifact_type:
        description: "Qué tipo de artefacto exportar"
        type: choice
        options:
          - application
          - package
        default: application
      artifact_id:
        description: "UUID del artefacto (opcional; si se omite se usará APP_UUID)"
        type: string
        required: false
      artifact_name:
        description: "Nombre del artefacto"
        type: string
        required: true
      source_env:
        description: "Ambiente origen"
        type: choice
        options:
          - DEV
          - QA
          - PROD
        default: DEV
      target_env:
        description: "Ambiente destino"
        type: choice
        options:
          - QA
          - PROD
        default: QA

jobs:
  export:
    name: Export from ${{ inputs.source_env }}
    uses: vrgroup-lab/appian-cicd-core/.github/workflows/export.yml@main
    with:
      base-url: ${{ vars[format('APPIAN_URL_{0}', inputs.source_env)] }}
      export-type: ${{ inputs.artifact_type }}
      uuid: ${{ inputs.artifact_id || vars.APP_UUID }}
      name: ${{ inputs.artifact_name }}
      download-out: export.zip
    secrets:
      APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}

  promote:
    name: Promote to ${{ inputs.target_env }}
    needs: export
    uses: vrgroup-lab/appian-cicd-core/.github/workflows/promote.yml@main
    with:
      base-url: ${{ vars[format('APPIAN_URL_{0}', inputs.target_env)] }}
      package-path: export.zip
    secrets:
      APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}

