name: Export App via core (sandbox)

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [dev, qa, prod]
        required: true
        description: "Target env"

permissions:
  id-token: write
  contents: read

jobs:
  validate-vars:
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.pick.outputs.uuid }}
    steps:
      - name: Validate APP_UUID
        id: pick
        shell: bash
        run: |
          UUID="${{ vars.APP_UUID }}"
          if [ -z "$UUID" ]; then
            echo "❌ Falta definir vars.APP_UUID en Settings → Secrets and variables → Actions → Variables"
            exit 1
          fi
          echo "uuid=$UUID" >> "$GITHUB_OUTPUT"
          echo "✅ Usando APP_UUID=$UUID"

  call-core-export:
    needs: validate-vars
    uses: vrgroup-lab/appian-cicd-core/.github/workflows/export-demo.yml@dev
    with:
      env:          ${{ github.event.inputs.env }}
      export_type:  application
      uuid:         ${{ needs.validate-vars.outputs.uuid }}
      name:         "CI Export application"
      description:  "Triggered by sandbox"
      download_artifacts: false