name: Deploy (Export + Promote)

on:
  workflow_dispatch:
    inputs:
      export_scope:
        description: "Qué desplegar"
        type: choice
        options: [app, package]
        default: app
      package_name:
        description: "Nombre del package (si export_scope=package)"
        required: false
      targets:
        description: "Ambientes destino"
        type: choice
        options: [qa, prod, qa+prod]
        default: qa

jobs:
  export_dev:
    name: Export from Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Core/export
        uses: mtombolini-vrgroup/appian-cicd-core/.github/workflows/export.yml@v1
        with:
          manifest_path: config/appian.json
          export_scope: ${{ inputs.export_scope }}
          package_name: ${{ inputs.package_name }}
          appian_url: ${{ vars.APPIAN_URL }}
          app_props_public_json: ${{ vars.APP_PROPS_PUBLIC_JSON }}
      secrets:
          APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}
          APP_PROPS_SENSITIVE_JSON: ${{ secrets.APP_PROPS_SENSITIVE_JSON }}

  promote_qa:
    if: ${{ inputs.targets == 'qa' || inputs.targets == 'qa+prod' }}
    name: Promote to QA
    needs: export_dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Core/promote (QA)
        uses: mtombolini-vrgroup/appian-cicd-core/.github/workflows/promote.yml@v1
        with:
          target_env: qa
          manifest_path: config/appian.json
          export_scope: ${{ inputs.export_scope }}
          package_name: ${{ inputs.package_name }}
          appian_url: ${{ vars.APPIAN_URL }}
          app_props_public_json: ${{ vars.APP_PROPS_PUBLIC_JSON }}
        secrets:
          APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}
          APP_PROPS_SENSITIVE_JSON: ${{ secrets.APP_PROPS_SENSITIVE_JSON }}

  promote_prod_after_qa:
    if: ${{ inputs.targets == 'qa+prod' }}
    name: Promote to Prod (after QA)
    needs: promote_qa
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Core/promote (Prod)
        uses: mtombolini-vrgroup/appian-cicd-core/.github/workflows/promote.yml@v1
        with:
          target_env: prod
          manifest_path: config/appian.json
          export_scope: ${{ inputs.export_scope }}
          package_name: ${{ inputs.package_name }}
          appian_url: ${{ vars.APPIAN_URL }}
          app_props_public_json: ${{ vars.APP_PROPS_PUBLIC_JSON }}
        secrets:
          APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}
          APP_PROPS_SENSITIVE_JSON: ${{ secrets.APP_PROPS_SENSITIVE_JSON }}

  promote_prod_direct:
    if: ${{ inputs.targets == 'prod' }}
    name: Promote to Prod (direct)
    needs: export_dev
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Core/promote (Prod)
        uses: mtombolini-vrgroup/appian-cicd-core/.github/workflows/promote.yml@v1
        with:
          target_env: prod
          manifest_path: config/appian.json
          export_scope: ${{ inputs.export_scope }}
          package_name: ${{ inputs.package_name }}
          appian_url: ${{ vars.APPIAN_URL }}
          app_props_public_json: ${{ vars.APP_PROPS_PUBLIC_JSON }}
        secrets:
          APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}
          APP_PROPS_SENSITIVE_JSON: ${{ secrets.APP_PROPS_SENSITIVE_JSON }}