name: Deploy App

on:
  workflow_dispatch:
    inputs:
      plan:
        description: Plan de promoción (sin dev-to-prod)
        type: choice
        options: [dev-to-qa, dev-qa-prod, qa-to-prod]
        default: dev-to-qa
      dry_run:
        description: Ejecutar promoción en modo dry-run
        type: choice
        options: ['false', 'true']
        default: 'false'

permissions:
  actions: write
  contents: write      # o write si lo necesitas
  pull-requests: write  # solo si el flujo crea PRs
  id-token: write
  issues: write 

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validar inputs y variables
        run: |
          echo "plan=${{ inputs.plan }}"
          if [ -z "${{ vars.APP_UUID }}" ]; then
            echo "❌ Falta la variable de repositorio APP_UUID. Defínela en Settings > Secrets and variables > Variables." >&2
            exit 1
          fi
          if [ -z "${{ vars.APP_NAME }}" ]; then
            echo "❌ Falta la variable de repositorio APP_NAME. Defínela en Settings > Secrets and variables > Variables." >&2
            exit 1
          fi


  export:
    needs: validate
    uses: vrgroup-lab/appian-cicd-core/.github/workflows/export.yml@icfbuild
    secrets: inherit
    with:
      # Si el plan es qa-to-prod, exportamos desde QA; si no, desde Dev
      env: ${{ inputs.plan == 'qa-to-prod' && 'qa' || 'dev' }}
      deploy_kind: app
      app_uuid: ${{ vars.APP_UUID }}
      app_name: ${{ vars.APP_NAME || '' }}
      dry_run: false

  archive_export:
    name: Guardar artefactos de export
    needs: export
    runs-on: ubuntu-latest
    outputs:
      artifact_dir: ${{ steps.publish.outputs.artifact_dir }}
      metadata_path: ${{ steps.publish.outputs.metadata_path }}
      icf_template_path: ${{ steps.locate_template.outputs.icf_template_path }}
    steps:
      - name: Checkout sandbox
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preparar carpeta destino
        id: prep
        env:
          EXPORT_ARTIFACT_NAME: ${{ needs.export.outputs.artifact_name }}
        run: |
          set -euo pipefail
          name="${EXPORT_ARTIFACT_NAME}"
          if [ -z "$name" ]; then
            name="export-${GITHUB_RUN_ID}"
          fi
          dest="appian-artifacts/$name"
          mkdir -p "$dest"
          echo "dest=$dest" >> "$GITHUB_OUTPUT"

      - name: Descargar paquete principal
        if: ${{ needs.export.outputs.artifact_name != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.export.outputs.artifact_name }}
          path: ${{ steps.prep.outputs.dest }}

      - name: Descargar metadata del export
        if: ${{ needs.export.outputs.artifact_name != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ format('{0}-meta', needs.export.outputs.artifact_name) }}
          path: ${{ steps.prep.outputs.dest }}

      - name: Descargar plantilla de customización
        if: ${{ needs.export.outputs.customization_template != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ format('{0}-customization-template', needs.export.outputs.artifact_name) }}
          path: ${{ steps.prep.outputs.dest }}/customization-template/raw

      - name: Extraer plantilla de customización
        if: ${{ needs.export.outputs.customization_template != '' }}
        env:
          SOURCE_DIR: ${{ steps.prep.outputs.dest }}/customization-template/raw
        run: |
          set -euo pipefail
          dir="${SOURCE_DIR}"
          echo "Contenido inicial de ${dir}:"
          ls -R "$dir" || true
          if [ ! -d "$dir" ]; then
            exit 0
          fi
          zip_file="$(find "$dir" -maxdepth 1 -type f -name '*.zip' -print -quit)"
          if [ -z "$zip_file" ]; then
            zip_file="$(find "$dir" -maxdepth 1 -type f -print -quit)"
          fi
          echo "Archivo detectado para extracción: ${zip_file:-<none>}"
          if [ -z "$zip_file" ]; then
            echo "No se encontró archivo comprimido de plantilla en ${dir}" >&2
            exit 0
          fi
          out_dir="$(dirname "$dir")/extracted"
          mkdir -p "$out_dir"
          unzip -oq "$zip_file" -d "$out_dir"
          echo "Contenido extraído en ${out_dir}:"
          ls -R "$out_dir" || true

      - name: Registrar metadata de export
        env:
          DEST: ${{ steps.prep.outputs.dest }}
          ARTIFACT_NAME: ${{ needs.export.outputs.artifact_name }}
          ARTIFACT_PATH: ${{ needs.export.outputs.artifact_path }}
          ARTIFACT_DIR: ${{ needs.export.outputs.artifact_dir }}
          MANIFEST_PATH: ${{ needs.export.outputs.manifest_path }}
          RAW_RESPONSE_PATH: ${{ needs.export.outputs.raw_response_path }}
          DEPLOYMENT_UUID: ${{ needs.export.outputs.deployment_uuid }}
          DEPLOYMENT_STATUS: ${{ needs.export.outputs.deployment_status }}
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import json
          import os
          from pathlib import Path

          dest_dir = Path(os.environ["DEST"])
          metadata_path = dest_dir / "export-metadata.json"

          def resolved_path(output_value: str, fallback_name: str) -> str:
              if not output_value:
                  return str(dest_dir / fallback_name)
              candidate = Path(output_value)
              # Preserve basename but point inside DEST so that the metadata describes local copy
              return str(dest_dir / candidate.name)


          artifact_name = os.environ.get("ARTIFACT_NAME", "")
          artifact_path_output = os.environ.get("ARTIFACT_PATH", "")
          artifact_zip_name = Path(artifact_path_output).name if artifact_path_output else f"{artifact_name}.zip"

          data = {
              "artifact_name": artifact_name,
              "artifact_path": str(dest_dir / artifact_zip_name),
              "artifact_dir": str(dest_dir),
              "manifest_path": resolved_path(os.environ.get("MANIFEST_PATH", ""), "export-manifest.json"),
              "raw_response_path": resolved_path(os.environ.get("RAW_RESPONSE_PATH", ""), "export-response.json"),
              "deployment_uuid": os.environ.get("DEPLOYMENT_UUID", ""),
              "deployment_status": os.environ.get("DEPLOYMENT_STATUS", ""),
          }

          metadata_path.parent.mkdir(parents=True, exist_ok=True)
          metadata_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
          PY

      - name: Localizar plantilla ICF
        id: locate_template
        env:
          DEST: ${{ steps.prep.outputs.dest }}
        run: |
          set -euo pipefail
          dest="${DEST}"
          path=""
          if [ -d "${dest}/customization-template/extracted" ]; then
            while IFS= read -r -d '' candidate; do
              echo "Evaluando candidato extraído: $candidate"
              if unzip -p "$candidate" >/dev/null 2>&1; then
                continue
              fi
              if file "$candidate" | grep -qi 'text'; then
                path="$candidate"
                break
              fi
            done < <(find "${dest}/customization-template/extracted" -type f \( -name '*.properties' -o -name 'icf*.txt' -o -name '*.txt' \) -print0)
          fi
          if [ -z "$path" ] && [ -d "${dest}/customization-template/raw" ]; then
            while IFS= read -r -d '' candidate; do
              echo "Evaluando candidato sin extraer: $candidate"
              if file "$candidate" | grep -qi 'text'; then
                path="$candidate"
                break
              fi
            done < <(find "${dest}/customization-template/raw" -type f \( -name '*.properties' -o -name 'icf*.txt' -o -name '*.txt' \) -print0)
          fi
          if [ -z "$path" ]; then
            path="$(find "${dest}" -maxdepth 1 -type f -name '*.properties' -print -quit || true)"
          fi
          if [ -n "$path" ]; then
            path="$(realpath "$path")"
            echo "Plantilla ICF localizada en: $path"
          else
            echo "No se encontró plantilla ICF en ${dest}" >&2
          fi
          echo "icf_template_path=${path}" >> "$GITHUB_OUTPUT"

      - name: Publicar rutas generadas
        id: publish
        env:
          DEST: ${{ steps.prep.outputs.dest }}
          ICF_TEMPLATE_PATH: ${{ steps.locate_template.outputs.icf_template_path }}
        run: |
          set -euo pipefail
          echo "artifact_dir=${DEST}" >> "$GITHUB_OUTPUT"
          echo "metadata_path=${DEST}/export-metadata.json" >> "$GITHUB_OUTPUT"
          if [ -n "${ICF_TEMPLATE_PATH}" ]; then
            echo "icf_template_path=${ICF_TEMPLATE_PATH}" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit artefactos
        env:
          DEST: ${{ steps.prep.outputs.dest }}
          ARTIFACT_NAME: ${{ needs.export.outputs.artifact_name }}
        run: |
          set -euo pipefail
          git status --short
          git add "$DEST"
          if git diff --cached --quiet; then
            echo "Sin cambios que versionar"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "chore: almacenar artefacto $ARTIFACT_NAME"
          git push

      - name: Mostrar detalles del deployment
        run: |
          echo "deployment_uuid=${{ needs.export.outputs.deployment_uuid }}"
          echo "deployment_status=${{ needs.export.outputs.deployment_status }}"

  icf_guidance:
    name: Registrar instrucciones ICF
    needs: archive_export
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.raise.outputs.issue_number }}
      issue_url: ${{ steps.raise.outputs.issue_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Crear issue con guía para ICF
        id: raise
        env:
          PLAN: ${{ inputs.plan }}
          DRY_RUN: ${{ inputs.dry_run }}
          ARTIFACT_DIR: ${{ needs.archive_export.outputs.artifact_dir }}
          METADATA_PATH: ${{ needs.archive_export.outputs.metadata_path }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TARGET_MAP: '{"dev-to-qa":["qa"],"dev-qa-prod":["qa","prod"],"qa-to-prod":["prod"]}'
          TEMPLATE_PATH: .github/templates/icf-issue.md
          PROVISIONING_TEMPLATE_PATH: provisioning/icf-template.properties
          ICF_TEMPLATE_PATH: ${{ needs.archive_export.outputs.icf_template_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/scripts/create_icf_issue.py

  promote_qa:
    if: ${{ inputs.plan == 'dev-to-qa' || inputs.plan == 'dev-qa-prod' }}
    needs: [export, archive_export, icf_guidance]
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Validar artifact de export
        run: |
          if [ -z "$ARTIFACT_NAME" ]; then
            echo "❌ Export no entregó artifact_name; no se puede promover." >&2
            exit 1
          fi
        env:
          ARTIFACT_NAME: ${{ needs.export.outputs.artifact_name }}

      - name: Descargar paquete/app
        id: download_package
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.export.outputs.artifact_name }}
          path: ${{ runner.temp }}/artifact

      - name: Determinar ruta del paquete/app
        id: package_path
        env:
          DOWNLOAD_DIR: ${{ steps.download_package.outputs.download-path }}
        run: |
          set -euo pipefail
          dir="${DOWNLOAD_DIR}"
          if [ -z "$dir" ]; then
            echo "No se pudo resolver la ruta de descarga del artefacto." >&2
            exit 1
          fi
          pkg="$(find "$dir" -maxdepth 1 -type f -name '*.zip' | head -n 1)"
          if [ -z "$pkg" ]; then
            pkg="$(find "$dir" -maxdepth 1 -type f | head -n 1)"
          fi
          if [ -z "$pkg" ]; then
            echo "No se encontró el artefacto exportado en $dir" >&2
            exit 1
          fi
          echo "package_path=$pkg" >> "$GITHUB_OUTPUT"

      - name: Construir ICF efímero
        id: build_icf
        uses: vrgroup-lab/appian-cicd-core/.github/actions/appian-build-icf@icfbuild
        env:
          ICF_JSON_OVERRIDES: ${{ secrets.ICF_JSON_OVERRIDES }}
        with:
          template_path: provisioning/icf-template.properties
          env: qa
          out_path: ${{ runner.temp }}/icf-qa.properties

      - name: Promover aplicación
        uses: vrgroup-lab/appian-cicd-core/.github/actions/appian-promote@icfbuild
        with:
          source_env: dev
          target_env: qa
          package_path: ${{ steps.package_path.outputs.package_path }}
          icf_path: ${{ steps.build_icf.outputs.icf_path }}
          dry_run: ${{ inputs.dry_run }}
        env:
          APPIAN_API_KEY_TARGET: ${{ secrets.APPIAN_API_KEY_TARGET }}

      - name: Cleanup ICF
        if: ${{ always() }}
        run: shred -u ${{ steps.build_icf.outputs.icf_path }} || true

  promote_prod_after_qa:
    if: ${{ inputs.plan == 'dev-qa-prod' }}
    needs: [promote_qa, export]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Validar artifact de export
        run: |
          if [ -z "$ARTIFACT_NAME" ]; then
            echo "❌ Export no entregó artifact_name; no se puede promover." >&2
            exit 1
          fi
        env:
          ARTIFACT_NAME: ${{ needs.export.outputs.artifact_name }}

      - name: Descargar paquete/app
        id: download_package
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.export.outputs.artifact_name }}
          path: ${{ runner.temp }}/artifact

      - name: Determinar ruta del paquete/app
        id: package_path
        env:
          DOWNLOAD_DIR: ${{ steps.download_package.outputs.download-path }}
        run: |
          set -euo pipefail
          dir="${DOWNLOAD_DIR}"
          if [ -z "$dir" ]; then
            echo "No se pudo resolver la ruta de descarga del artefacto." >&2
            exit 1
          fi
          pkg="$(find "$dir" -maxdepth 1 -type f -name '*.zip' | head -n 1)"
          if [ -z "$pkg" ]; then
            pkg="$(find "$dir" -maxdepth 1 -type f | head -n 1)"
          fi
          if [ -z "$pkg" ]; then
            echo "No se encontró el artefacto exportado en $dir" >&2
            exit 1
          fi
          echo "package_path=$pkg" >> "$GITHUB_OUTPUT"

      - name: Construir ICF efímero
        id: build_icf
        uses: vrgroup-lab/appian-cicd-core/.github/actions/appian-build-icf@icfbuild
        env:
          ICF_JSON_OVERRIDES: ${{ secrets.ICF_JSON_OVERRIDES }}
        with:
          template_path: provisioning/icf-template.properties
          env: prod
          out_path: ${{ runner.temp }}/icf-prod.properties

      - name: Promover aplicación
        uses: vrgroup-lab/appian-cicd-core/.github/actions/appian-promote@icfbuild
        with:
          source_env: dev
          target_env: prod
          package_path: ${{ steps.package_path.outputs.package_path }}
          icf_path: ${{ steps.build_icf.outputs.icf_path }}
          dry_run: ${{ inputs.dry_run }}
        env:
          APPIAN_API_KEY_TARGET: ${{ secrets.APPIAN_API_KEY_TARGET }}

      - name: Cleanup ICF
        if: ${{ always() }}
        run: shred -u ${{ steps.build_icf.outputs.icf_path }} || true

  promote_prod_from_qa:
    if: ${{ inputs.plan == 'qa-to-prod' }}
    needs: [export, archive_export, icf_guidance]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Validar artifact de export
        run: |
          if [ -z "$ARTIFACT_NAME" ]; then
            echo "❌ Export no entregó artifact_name; no se puede promover." >&2
            exit 1
          fi
        env:
          ARTIFACT_NAME: ${{ needs.export.outputs.artifact_name }}

      - name: Descargar paquete/app
        id: download_package
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.export.outputs.artifact_name }}
          path: ${{ runner.temp }}/artifact

      - name: Determinar ruta del paquete/app
        id: package_path
        env:
          DOWNLOAD_DIR: ${{ steps.download_package.outputs.download-path }}
        run: |
          set -euo pipefail
          dir="${DOWNLOAD_DIR}"
          if [ -z "$dir" ]; then
            echo "No se pudo resolver la ruta de descarga del artefacto." >&2
            exit 1
          fi
          pkg="$(find "$dir" -maxdepth 1 -type f -name '*.zip' | head -n 1)"
          if [ -z "$pkg" ]; then
            pkg="$(find "$dir" -maxdepth 1 -type f | head -n 1)"
          fi
          if [ -z "$pkg" ]; then
            echo "No se encontró el artefacto exportado en $dir" >&2
            exit 1
          fi
          echo "package_path=$pkg" >> "$GITHUB_OUTPUT"

      - name: Construir ICF efímero
        id: build_icf
        uses: vrgroup-lab/appian-cicd-core/.github/actions/appian-build-icf@icfbuild
        env:
          ICF_JSON_OVERRIDES: ${{ secrets.ICF_JSON_OVERRIDES }}
        with:
          template_path: provisioning/icf-template.properties
          env: prod
          out_path: ${{ runner.temp }}/icf-prod.properties

      - name: Promover aplicación
        uses: vrgroup-lab/appian-cicd-core/.github/actions/appian-promote@icfbuild
        with:
          source_env: qa
          target_env: prod
          package_path: ${{ steps.package_path.outputs.package_path }}
          icf_path: ${{ steps.build_icf.outputs.icf_path }}
          dry_run: ${{ inputs.dry_run }}
        env:
          APPIAN_API_KEY_TARGET: ${{ secrets.APPIAN_API_KEY_TARGET }}

      - name: Cleanup ICF
        if: ${{ always() }}
        run: shred -u ${{ steps.build_icf.outputs.icf_path }} || true
