name: Export (Dev)
on:
  workflow_dispatch:
    inputs:
      export_scope:
        description: "¿Qué exportar?"
        type: choice
        options: [app, package]
        default: app
      package_name:
        description: "Nombre del package (si export_scope=package)"
        required: false

jobs:
  export:
    uses: vrgroup-lab/appian-cicd-core/.github/workflows/export.yml@develop
    with:
      manifest_path: config/appian.json
      export_scope: ${{ inputs.export_scope }}
      package_name: ${{ inputs.package_name }}
      appian_url: ${{ vars.APPIAN_URL }}
      app_props_public_json: ${{ vars.APP_PROPS_PUBLIC_JSON }}
    secrets: inherit